### ISSUE TITLE
弱弱请教一个问题

### ISSUE THREAD

**Issue by ijackwu** [hanpanpan200/RN-android-download-share#1]

**Comment by chaorenluo** [comment]
这个demo编译不过 请问咋处理
* Where:
Build file 'E:\RN-android-download-share\node_modules\react-native-share\android\build.gradle' line: 53

* What went wrong:
A problem occurred evaluating project ':react-native-share'.
> Could not find method compileOnly() for arguments [com.facebook.react:react-native:+] on project ':react-native-share'.
